# Generated by Django 5.2.1 on 2025-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
