# Generated by Django 5.2.1 on 2025-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0002_tweet_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
