# Generated by Django 5.2.1 on 2025-06-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inapp', '0003_tweet_is_approved_tweet_is_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_approved',
        ),
    ]
